spring.application.name=kafkaboard
spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.jwtucgtlouqpgvgexrsh
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=kafkaboard
spring.jpa.open-in-view=false
spring.flyway.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres
spring.flyway.user=postgres.jwtucgtlouqpgvgexrsh
spring.flyway.password=${DB_PASSWORD}
spring.flyway.schemas=kafkaboard
spring.flyway.default-schema=kafkaboard
spring.flyway.create-schemas=true
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
